# Generated by Django 4.2.7 on 2023-11-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_author_book_genre_mymodelname_bookinstance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModelName',
        ),
    ]
