# Generated by Django 4.2.7 on 2023-11-23 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0005_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='name',
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
