# Generated by Django 4.2.7 on 2024-02-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_book_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='portada',
        ),
    ]
