# Generated by Django 4.2.7 on 2024-02-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_book_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='portada',
            field=models.ImageField(blank=True, height_field=400, null=True, upload_to='portadas', width_field=400),
        ),
    ]
