# Generated by Django 4.2.7 on 2024-02-11 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_alter_book_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='PDF',
            new_name='pdf',
        ),
    ]
