# Generated by Django 4.2.7 on 2024-02-21 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_alter_person_age_alter_person_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_search', 'Can search books'),)},
        ),
    ]
