# Generated by Django 4.2.7 on 2024-02-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('permibusca', 'Can search books exam'),)},
        ),
    ]
