# Generated by Django 4.2.7 on 2024-02-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('permirenovar', 'puede renovar libros'),)},
        ),
    ]
